# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.

Tips: 
  1. Configuration of Workspace: https://k0nze.dev/posts/python-relative-imports-vscode/#:%7E:text=Inside%20the-,launch.json,-you%20have%20to
"""
import matplotlib.pyplot as plt

from sources.canvas import Canvas
from sources.utils import BoundingBox
from sources.generators import *

def testGenerator():
  n = int(input("Enter the desired number of points: "))

  points = random_points_on_axes(n)
  bbox = BoundingBox()
  bbox.reshape(points)
  bbox.scale(1.25)
  canvas = Canvas(bbox)

  canvas.begin()
  for p in points:
    canvas.draw_point(p)
  canvas.end()
  canvas.close()

  points = random_points_in_square(n)
  bbox = BoundingBox()
  bbox.reshape(points)
  bbox.scale(1.25)
  canvas = Canvas(bbox)

  canvas.begin()
  for p in points:
    canvas.draw_point(p)
  canvas.end()
  canvas.close()

  points = random_points_in_disc(n)
  bbox = BoundingBox()
  bbox.reshape(points)
  bbox.scale(1.25)
  canvas = Canvas(bbox)

  canvas.begin()
  for p in points:
    canvas.draw_point(p)
  canvas.end()
  canvas.close()

  points = random_points_on_parabola(n)
  bbox = BoundingBox()
  bbox.reshape(points)
  bbox.scale(1.25)
  canvas = Canvas(bbox)

  canvas.begin()
  for p in points:
    canvas.draw_point(p)
  canvas.end()
  canvas.close()

if __name__ == '__main__':
  testGenerator()
