# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.
"""
from sources.stars import StarVertices

def testStarVertices():
  t = StarVertices()

  for i in range(9):
    t.addVertex()

  # infinite faces
  t.addFace(6,0,3)
  t.addFace(2,0,6)
  t.addFace(4,7,0)
  t.addFace(1,4,0)
  t.addFace(5,0,2)
  t.addFace(0,5,1)
  t.addFace(7,3,0)

  # check if convex hull is OK
  halls = map(str, 2*[1,4,7,3,6,2,5])
  hull  = map(str, t._vertices[0]._links[0][:-1])
  assert ''.join(hull) in ''.join(halls)

  # finite faces
  t.addFace(1,5,4)
  t.addFace(3,8,6)
  t.addFace(9,5,2)
  t.addFace(4,8,7)
  t.addFace(9,2,6)
  t.addFace(4,9,8)
  t.addFace(5,9,4)
  t.addFace(9,6,8)
  t.addFace(8,3,7)

  print("BEFORE")
  t.print()

  # remove algumas faces para testar
  # infinite faces
  t.deleteFace(6,0,3)
  t.deleteFace(2,0,6)
  t.deleteFace(4,7,0)
  t.deleteFace(1,4,0)
  t.deleteFace(5,0,2)
  t.deleteFace(0,5,1)
  t.deleteFace(7,3,0)

  # finite faces
  t.deleteFace(1,5,4)
  t.deleteFace(3,8,6)
  t.deleteFace(9,5,2)
  t.deleteFace(4,8,7)
  t.deleteFace(9,2,6)
  t.deleteFace(4,9,8)
  t.deleteFace(5,9,4)
  t.deleteFace(9,6,8)
  t.deleteFace(8,3,7)
  print("AFTER")
  t.print()


if __name__ == '__main__':
  testStarVertices()
