# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.
"""
import numpy
import copy
from enum import Enum

from .utils import Point

# Sorting methods
class SortingMethod(Enum):
  NONE    = 0
  RANDOM  = 1
  HILBERT = 2
  KDTREE  = 3

# Temporarily, we have only implemented NONE and RANDOM.
class Brio:
  def __init__(self, method = SortingMethod.RANDOM):
    print("> creating BRIO functor")
    self.__method = method

  def __call__(self, points):
    assert isinstance(points, numpy.ndarray)
    P = copy.deepcopy(points)
    if self.__method == SortingMethod.NONE:
      return P
    if self.__method == SortingMethod.RANDOM:
      numpy.random.shuffle(P)
      print("  | random shuffle done.")
      return P
    
    return None