# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.
"""

import matplotlib.pyplot as plt

from .utils import Point

def drawPoint(fig, p):
  plt.figure(fig)
  plt.plot(p.x, p.y, 'ro', linewidth=3)

def drawSegment(fig, p, q):
  plt.figure(fig)
  plt.plot([p.x, q.x], [p.y, q.y], 'r-', linewidth=3, zorder=3)

def drawTriangle(fig, p, q, r, filled=False):
  plt.figure(fig)
  x = [p.x, q.x, r.x]
  y = [p.y, q.y, r.y]

  if filled:
    plt.fill(x, y, 'b', facecolor='magenta', edgecolor='none', alpha=0.2, zorder=1)
  else:
    plt.fill(x, y, 'b', facecolor='none', edgecolor='blue', linewidth=1.5, zorder=2)